### ISSUE TITLE
Memory leak when the same never-resolved Promise is used with thousands of calls to Promise.race()

### ISSUE THREAD

**Issue by dko-slapdash** [fraxken/combine-async-iterators#4]
https://github.com/fraxken/combine-async-iterators/blob/f47bea22a56dfa3bd88e06d5cbf2885477b23af6/index.js#L26

Details, why:
https://github.com/nodejs/node/issues/17469

Alternative approach:
https://github.com/reconbot/streaming-iterables/blob/master/lib/parallel-merge.ts
(but for now streaming-iterables doesn't run .return() and your library does, which is a big advantage of your library).

**Comment by fraxken** [comment]
fixed with v2.0.0.
